### PR TITLE
fix(instrumentation-remix): handle undefined action keys correctly

### LINKED ISSUE #43: FormData should not be automatically instrumented
Currently, this library automatically tracks formData values as attributes on spans. This should at the least be configurable - sensitive data such as passwords etc may be passed by applications through formData and that data should not be recorded

### PR DESCRIPTION
**Pull request by backjo**
Closes #43

### CODE REVIEW

File: packages/instrumentation-remix/src/instrumentation.ts [hunk 1]
```diff
@@ -426,7 +426,7 @@ export class RemixInstrumentation extends InstrumentationBase {
                   const formData = await clonedRequest.formData();
                   const { actionFormDataAttributes: actionFormAttributes } = plugin.getConfig();
                   formData.forEach((value, key) => {
-                    if (actionFormAttributes[key] !== false) {
+                    if (actionFormAttributes[key] && actionFormAttributes[key] !== false) {
```
Comment (chonigbe) [inline packages/instrumentation-remix/src/instrumentation.ts:429]: any chance we should do a check for falsy values instead of direct check against false?
```suggestion
                    if (actionFormAttributes[key] && !!actionFormAttributes[key] !== false) {
```

Comment (chonigbe) [reply packages/instrumentation-remix/src/instrumentation.ts:429]: nevermind, ignore.

**Review by justindsmith — APPROVED** [review]
